# Generated by Django 3.2.3 on 2021-06-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210531_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.BigIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='favour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feedback.favour'),
        ),
    ]
