# Generated by Django 3.2.3 on 2021-06-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210608_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='favour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.favour'),
        ),
    ]
