# Generated by Django 3.2.2 on 2021-05-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_rename_user_aplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.BigIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='aplications',
            options={'verbose_name_plural': 'Заявки пользователей'},
        ),
        migrations.AlterField(
            model_name='aplications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заяки'),
        ),
        migrations.AlterField(
            model_name='aplications',
            name='favour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.favour'),
        ),
    ]
