# Generated by Django 3.2.3 on 2021-05-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_auto_20210507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplications',
            name='favour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.favour', verbose_name='Название услуги, цена'),
        ),
    ]
